environment:
  matrix:
    # - OS: win64
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   QT_PATH: C:\Qt\5.14\msvc2017_64
    #   ARCH: x64
    # - OS: win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   QT_PATH: C:\Qt\5.14\msvc2017
    #   ARCH: x86
    # - OS: macOS
    #   APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
    - OS: linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

install:
  - cmd: .ci/install.bat
  - sh: .ci/install.sh

before_build:
  - cmd: set PATH=%QT_PATH%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - cmd: call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat %ARCH%
  - cmd: .ci/before_build.bat
  - sh: .ci/before_build.sh

build_script:
  - cmd: .ci/build.bat
  - sh: .ci/build.sh

after_build:
  - cmd: .ci/after_build.bat
  - sh: .ci/after_build.sh

artifacts:
  - path: EonTimer-%OS%.zip
  - path: EonTimer-%OS%.zip.sha256
