environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
    OS: macOS
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.14\msvc2017_64
    OS: win64
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.14\msvc2017
    OS: win32
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    OS: linux

install:
    - git submodule update --init --recursive    
    
before_build:
    # macOS
    - sh: brew install qt5 sfml
    # Windows
    - cmd: set PATH=%QTPATH%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call %VCVARSALLPATH% %VCVARSALL%
    # Linux
    - sh: sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-bionic -y
    - sh: sudo apt-get update -qq
    - sh: sudo apt-get -y install qt514base qt514svg qt514tools libgl1-mesa-dev libsfml-dev
    - sh: source /opt/qt5*/bin/qt5*-env.sh
    
build_script:
    - qmake EonTimer.pro
    # Windows
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: make -j $(nproc)
    # macOS
    - sh: make -j $(sysctl -n hw.phyiscalcpu)
    
after_build:
    # Windows
    - cmd: md EonTimer-windows
    - cmd: move release\EonTimer.exe EonTimer-windows\EonTimer.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw EonTimer-windows\EonTimer.exe
    - cmd: del EonTimer-windows\vc_redist*.exe
    - cmd: xcopy /I %QTPATH%\plugins\platforms\qwindows.dll EonTimer-windows\platforms\
    - cmd: xcopy /I %QTPATH%\plugins\styles\qwindowsvistastyle.dll EonTimer-windows\styles\
    - cmd: xcopy /I %OpenSSL%\libcrypto*.dll EonTimer-windows\
    - cmd: xcopy /I %OpenSSL%\libssl*.dll EonTimer-windows\
    - cmd: 7z a EonTimer-%OS%.zip EonTimer-windows\
    - cmd: sha256sum EonTimer-%OS%.zip > EonTimer-%OS%.zip.sha256
    # Linux
    - sh: zip -r EonTimer-linux.zip EonTimer
    - sh: sha256sum EonTimer-linux.zip > EonTimer-linux.zip.sha256
    # macOS
    - sh: zip -r EonTimer-macOS.zip EonTimer.app
    - sh: shasum -a 256 EonTimer-macOS.zip > EonTimer-macOS.zip.sha256
    
artifacts:
- path: EonTimer-%OS%.zip
- path: EonTimer-%OS%.zip.sha256

# deploy:
#     provider: GitHub
#     description: ''
#     auth_token:
#         secure: u3c5wUq11csZ77TpgKMImu9U+ibNiviMcEpTuQXmqp1YGSHA/+u5FhqZ3KRZBAQX
#     artifact: PokeFinder-%OS%.zip,PokeFinder-%OS%.zip.sha256
#     on:
#         APPVEYOR_REPO_TAG: true