name: Build

on: push

concurrency:
  group: build-${{ inputs.git-ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      - run: pyinstaller EonTimer.spec

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos' }}
        with:
          name: macos
          path: dist/EonTimer.app

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu' }}
        with:
          name: ubuntu
          path: dist/EonTimer

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows' }}
        with:
          name: windows
          path: dist/EonTimer.exe


