name: Build

on: push

concurrency:
  group: build-${{ inputs.git-ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - run: pip install -r requirements.txt

      - run: pyinstaller EonTimer.spec

      - id: artifact
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos" ]]; then
            hdiutil create -format UDZO -srcfolder dist/EonTimer.app dist/EonTimer.dmg
            echo "artifact_name=dist/EonTimer.dmg" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.os }}" == "windows" ]]; then
            echo "artifact_name=dist/EonTimer.exe" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.os }}" == "ubuntu" ]]; then
            echo "artifact_name=dist/EonTimer" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: EonTimer-${{ matrix.os }}
          path: ${{ steps.artifact.outputs.artifact_name }}

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.artifact.outputs.artifact_name }}
