name: Build

on: push

concurrency:
  group: build-${{ inputs.git-ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - macos-latest
      - ubuntu-latest
      - windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: pyinstaller eon-timer.spec
      - run: ls -l dist
